//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookImplement.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookImplement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _00_P {
            get {
                object obj = ResourceManager.GetObject("_00_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _01_F {
            get {
                object obj = ResourceManager.GetObject("_01_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _02_E {
            get {
                object obj = ResourceManager.GetObject("_02_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _03_D {
            get {
                object obj = ResourceManager.GetObject("_03_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _04_C {
            get {
                object obj = ResourceManager.GetObject("_04_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _05_B {
            get {
                object obj = ResourceManager.GetObject("_05_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _06_A {
            get {
                object obj = ResourceManager.GetObject("_06_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _07_9 {
            get {
                object obj = ResourceManager.GetObject("_07_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _08_8 {
            get {
                object obj = ResourceManager.GetObject("_08_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _09_7 {
            get {
                object obj = ResourceManager.GetObject("_09_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _10_6 {
            get {
                object obj = ResourceManager.GetObject("_10_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_ok {
            get {
                object obj = ResourceManager.GetObject("button_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap critical {
            get {
                object obj = ResourceManager.GetObject("critical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   체력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect1 {
            get {
                return ResourceManager.GetString("Effect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다이어트 효과 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect10 {
            get {
                return ResourceManager.GetString("Effect10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect2 {
            get {
                return ResourceManager.GetString("Effect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   솜씨 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect3 {
            get {
                return ResourceManager.GetString("Effect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의지 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect4 {
            get {
                return ResourceManager.GetString("Effect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행운 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect5 {
            get {
                return ResourceManager.GetString("Effect5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대생명력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect6 {
            get {
                return ResourceManager.GetString("Effect6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대마나 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect7 {
            get {
                return ResourceManager.GetString("Effect7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대스태미너 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect8 {
            get {
                return ResourceManager.GetString("Effect8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스태미너 회복도 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Effect9 {
            get {
                return ResourceManager.GetString("Effect9", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   계속 진행하려면 아무 키나 누르세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgContinue {
            get {
                return ResourceManager.GetString("MsgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 되었습니다. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCopied {
            get {
                return ResourceManager.GetString("MsgCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 데이터의 형식이 잘못 되었습니다. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDataInvalid {
            get {
                return ResourceManager.GetString("MsgDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 입수 방법을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInsertStuffHowToGet {
            get {
                return ResourceManager.GetString("MsgInsertStuffHowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 이름을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInsertStuffName {
            get {
                return ResourceManager.GetString("MsgInsertStuffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 가격을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInsertStuffPrice {
            get {
                return ResourceManager.GetString("MsgInsertStuffPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   케이틴 = 0, 글리니스 = 1, 세나 = 2, 글루아스 = 3, 리리스 = 4,
        ///에피 = 5, 제니퍼 = 6, 루와이 = 7, 피에릭 = 8, 글라니테스 = 9,
        ///고든 = 10, 프레이저 = 11, 반스트 = 12, 채집 = 13, 요리 = 14, 
        ///루카스 = 15, 카독 = 16 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgLegend {
            get {
                return ResourceManager.GetString("MsgLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파이 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank6 {
            get {
                return ResourceManager.GetString("Rank6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잼 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank7 {
            get {
                return ResourceManager.GetString("Rank7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파스타 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank8 {
            get {
                return ResourceManager.GetString("Rank8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   볶기 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank9 {
            get {
                return ResourceManager.GetString("Rank9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   튀기기 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankA {
            get {
                return ResourceManager.GetString("RankA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   면 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankB {
            get {
                return ResourceManager.GetString("RankB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   끓이기 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankC {
            get {
                return ResourceManager.GetString("RankC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반죽 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankD {
            get {
                return ResourceManager.GetString("RankD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삶기 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankE {
            get {
                return ResourceManager.GetString("RankE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   굽기 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankF {
            get {
                return ResourceManager.GetString("RankF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   혼합 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RankP {
            get {
                return ResourceManager.GetString("RankP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   케이틴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller00 {
            get {
                return ResourceManager.GetString("Seller00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글리니스 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller01 {
            get {
                return ResourceManager.GetString("Seller01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세나 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller02 {
            get {
                return ResourceManager.GetString("Seller02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글루아스 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller03 {
            get {
                return ResourceManager.GetString("Seller03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리리스 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller04 {
            get {
                return ResourceManager.GetString("Seller04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에피 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller05 {
            get {
                return ResourceManager.GetString("Seller05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제니퍼 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller06 {
            get {
                return ResourceManager.GetString("Seller06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   루와이 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller07 {
            get {
                return ResourceManager.GetString("Seller07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   피에릭 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller08 {
            get {
                return ResourceManager.GetString("Seller08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글라니테스 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller09 {
            get {
                return ResourceManager.GetString("Seller09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고든 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller10 {
            get {
                return ResourceManager.GetString("Seller10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프레이저 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller11 {
            get {
                return ResourceManager.GetString("Seller11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반스트 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller12 {
            get {
                return ResourceManager.GetString("Seller12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채집 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller13 {
            get {
                return ResourceManager.GetString("Seller13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요리 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller14 {
            get {
                return ResourceManager.GetString("Seller14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   루카스 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller15 {
            get {
                return ResourceManager.GetString("Seller15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카독 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seller16 {
            get {
                return ResourceManager.GetString("Seller16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrInfo {
            get {
                return ResourceManager.GetString("StrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrNothing {
            get {
                return ResourceManager.GetString("StrNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요리재료 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrStuff {
            get {
                return ResourceManager.GetString("StrStuff", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
