//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookImplement.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookImplement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _00_P {
            get {
                object obj = ResourceManager.GetObject("_00_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01_F {
            get {
                object obj = ResourceManager.GetObject("_01_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02_E {
            get {
                object obj = ResourceManager.GetObject("_02_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _03_D {
            get {
                object obj = ResourceManager.GetObject("_03_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _04_C {
            get {
                object obj = ResourceManager.GetObject("_04_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _05_B {
            get {
                object obj = ResourceManager.GetObject("_05_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _06_A {
            get {
                object obj = ResourceManager.GetObject("_06_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _07_9 {
            get {
                object obj = ResourceManager.GetObject("_07_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _08_8 {
            get {
                object obj = ResourceManager.GetObject("_08_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _09_7 {
            get {
                object obj = ResourceManager.GetObject("_09_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _10_6 {
            get {
                object obj = ResourceManager.GetObject("_10_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   체력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect1 {
            get {
                return ResourceManager.GetString("Effect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다이어트 효과 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect10 {
            get {
                return ResourceManager.GetString("Effect10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect2 {
            get {
                return ResourceManager.GetString("Effect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   솜씨 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect3 {
            get {
                return ResourceManager.GetString("Effect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의지 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect4 {
            get {
                return ResourceManager.GetString("Effect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행운 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect5 {
            get {
                return ResourceManager.GetString("Effect5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대생명력 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect6 {
            get {
                return ResourceManager.GetString("Effect6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대마나 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect7 {
            get {
                return ResourceManager.GetString("Effect7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대스태미너 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect8 {
            get {
                return ResourceManager.GetString("Effect8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스태미너 회복도 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Effect9 {
            get {
                return ResourceManager.GetString("Effect9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계속 진행하려면 아무 키나 누르세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgContinue {
            get {
                return ResourceManager.GetString("MsgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 되었습니다. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgCopied {
            get {
                return ResourceManager.GetString("MsgCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 데이터의 형식이 잘못 되었습니다. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDataInvalid {
            get {
                return ResourceManager.GetString("MsgDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 입수 방법을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInsertStuffHowToGet {
            get {
                return ResourceManager.GetString("MsgInsertStuffHowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 이름을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInsertStuffName {
            get {
                return ResourceManager.GetString("MsgInsertStuffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재료 가격을 입력하세요. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInsertStuffPrice {
            get {
                return ResourceManager.GetString("MsgInsertStuffPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   케이틴 = 0, 글리니스 = 1, 세나 = 2, 글루아스 = 3, 리리스 = 4,
        ///에피 = 5, 제니퍼 = 6, 루와이 = 7, 피에릭 = 8, 글라니테스 = 9,
        ///반스트 = 10, 고든 = 11, 프레이저 = 12, 채집 = 13, 요리 = 14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgLegend {
            get {
                return ResourceManager.GetString("MsgLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StrInfo {
            get {
                return ResourceManager.GetString("StrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StrNothing {
            get {
                return ResourceManager.GetString("StrNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요리재료 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StrStuff {
            get {
                return ResourceManager.GetString("StrStuff", resourceCulture);
            }
        }
    }
}
